version: "3"

services:
  postgres:
    image: postgres:11.1
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - "./.data/postgres:/var/lib/postgresql"
